import java.util.Scanner;
class Random{ //Used to generate a random number between 1 to 100 using a constructor.
    int guess_it;
    public Random(){
        guess_it=(int)(Math.floor(Math.random()*(100)+1));
    }
    public int getGuessIt(){ //Used to return the generated number to main method.
        return guess_it;
    }
}
class NoOfGuesses{
    private static int no_of_guesses=1;
    public static void setNoOfGuesses(int a,int b){ //Used to calculate the score of the player. a stores user input and b stores the number generated by the computer.
        if(a>b)
            System.out.println("You guess is greater than the actual number, try again.");
        else
            System.out.println("You guess is smaller than the actual number, try again.");
        no_of_guesses++;
    }
    public static int getNoOfGuesses(){ //Used to return the score of the player to the main method.
        return no_of_guesses;
    }

}
public class GuessTheNumber
{
    public static int userInput(){ //Used to take user's input.
        Scanner in=new Scanner(System.in);
        System.out.println("Enter a number between 1 and 100 : ");
        int user_input=in.nextInt();
        return user_input;
    }
    public static boolean isCorrect(int n, int m){ //Used to check if the user has guessed the number correctly.
        if(n==m)
            return true;
        else
            return false;
    }
    public static void main(String[] args) {
        System.out.println("Welcome to my Guess The Number game.\nIn this game, the computer will generate a number between 1 to 100 (both inclusive).\nYour task is to guess the number generated by the computer.\nYou will be told if your guess is correct.\nScore will be printed once you guess the number.\nThe lower the score, the better you are");
        Random obj=new Random();
        int guess=obj.getGuessIt();
        boolean check;
        while (true){
            int input=GuessTheNumber.userInput();
            check=GuessTheNumber.isCorrect(input,guess);
            if(check==true)
            {
                System.out.println("Your score is : "+NoOfGuesses.getNoOfGuesses());
                break;
            }
            else
            {
                NoOfGuesses.setNoOfGuesses(input,guess);
            }
        }
    }
}
